#!/usr/bin/env python3
"""Run an on-policy Gated-GRPO loop for OP-VEC task-vector coefficients.

This script intentionally keeps the algorithm small and auditable:

1. collect rollouts from the current gated policy on prompt-only calibration data;
2. score each response with the existing verifier reward router;
3. update only the OP-VEC gate/coefficient module with a GRPO clipped loss;
4. feed the new gate checkpoint into the next iteration.

It is a lightweight OP-VEC-native loop.  The rollout/reward semantics mirror
VeRL/slime GRPO, but the trainable parameters are the task-vector coefficients
instead of the full LM weights.
"""

from __future__ import annotations

import argparse
import json
import shlex
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]


def main() -> None:
    args = parse_args()
    run_dir = Path(args.run_dir).expanduser().resolve()
    run_dir.mkdir(parents=True, exist_ok=True)
    gate_checkpoint = args.init_gate_checkpoint
    manifest = {
        "format": "opvec_gated_grpo_loop_v1",
        "created_at": datetime.now(timezone.utc).isoformat(),
        "config": args.config,
        "mode_manifest": args.mode_manifest,
        "run_dir": str(run_dir),
        "iterations": [],
        "notes": [
            "Rollouts are generated by the current gated policy; base/expert/TA rollouts should be used only for prompt mining or diagnostics.",
            "Only OP-VEC gate/coefficient parameters are optimized; base and expert task-vector deltas remain frozen.",
        ],
    }

    for iteration in range(1, args.num_iters + 1):
        iter_dir = run_dir / f"iter_{iteration:03d}"
        iter_dir.mkdir(parents=True, exist_ok=True)
        rollouts = iter_dir / "rollouts.jsonl"
        updates = iter_dir / "gate_updates.jsonl"

        collect_cmd = _collect_command(args, rollouts=rollouts, gate_checkpoint=gate_checkpoint, iteration=iteration)
        update_cmd = _update_command(
            args,
            rollouts=rollouts,
            updates=updates,
            gate_checkpoint=gate_checkpoint,
            iteration=iteration,
        )

        if args.dry_run:
            print("[dry-run]", _fmt_cmd(collect_cmd))
            print("[dry-run]", _fmt_cmd(update_cmd))
        else:
            _run(collect_cmd)
            _run(update_cmd)

        next_gate = updates.with_suffix(".gates.json")
        summary_path = updates.with_suffix(".summary.json")
        iter_summary = {
            "iteration": iteration,
            "rollouts": str(rollouts),
            "updates": str(updates),
            "input_gate_checkpoint": gate_checkpoint,
            "output_gate_checkpoint": str(next_gate),
            "collect_command": collect_cmd,
            "update_command": update_cmd,
        }
        if summary_path.exists():
            try:
                iter_summary["update_summary"] = json.loads(summary_path.read_text(encoding="utf-8"))
            except Exception as error:  # pragma: no cover - audit fallback
                iter_summary["update_summary_error"] = str(error)
        manifest["iterations"].append(iter_summary)
        gate_checkpoint = str(next_gate)
        _write_json(run_dir / "gated_grpo_loop_manifest.json", manifest)

    if args.bake_final and gate_checkpoint:
        output_dir = Path(args.bake_output or (run_dir / "baked_final_checkpoint"))
        bake_cmd = [
            sys.executable,
            str(REPO_ROOT / "scripts/eval/opvec_bake_checkpoint.py"),
            "--config",
            args.config,
            "--mode-manifest",
            args.mode_manifest,
            "--gate-checkpoint",
            gate_checkpoint,
            "--output",
            str(output_dir),
        ]
        if args.plan_only_bake:
            bake_cmd.append("--plan-only")
        if args.dry_run:
            print("[dry-run]", _fmt_cmd(bake_cmd))
        else:
            _run(bake_cmd)
        manifest["bake"] = {"command": bake_cmd, "gate_checkpoint": gate_checkpoint, "output": str(output_dir)}
        _write_json(run_dir / "gated_grpo_loop_manifest.json", manifest)

    print(json.dumps({"run_dir": str(run_dir), "final_gate_checkpoint": gate_checkpoint}, ensure_ascii=False, indent=2))


def _collect_command(args: argparse.Namespace, *, rollouts: Path, gate_checkpoint: str | None, iteration: int) -> list[str]:
    cmd = [
        sys.executable,
        str(REPO_ROOT / "scripts/train/opvec_collect_hf_rollouts.py"),
        "--config",
        args.config,
        "--mode-manifest",
        args.mode_manifest,
        "--output",
        str(rollouts),
        "--run-id",
        f"{args.run_id}-iter{iteration:03d}",
        "--num-prompts",
        str(args.num_prompts),
        "--samples-per-prompt",
        str(args.samples_per_prompt),
        "--max-new-tokens",
        str(args.max_new_tokens),
        "--max-prompt-tokens",
        str(args.max_prompt_tokens),
        "--max-logprob-tokens",
        str(args.max_logprob_tokens),
        "--temperature",
        str(args.temperature),
        "--top-p",
        str(args.top_p),
        "--seed",
        str(args.seed + iteration - 1),
        "--device",
        args.device,
        "--torch-dtype",
        args.torch_dtype,
        "--gate-parameterization",
        args.gate_parameterization,
        "--stream-output",
        "--progress-every",
        str(args.progress_every),
    ]
    if args.seed_manifest:
        cmd += ["--seed-manifest", args.seed_manifest]
    if args.tasks:
        cmd += ["--tasks", args.tasks]
    if args.memory_kind:
        cmd += ["--memory-kind", args.memory_kind]
    if args.prompt_id:
        cmd += ["--prompt-id", args.prompt_id]
    if args.use_manifest_order:
        cmd.append("--use-manifest-order")
    if args.greedy:
        cmd.append("--greedy")
    if args.device_map:
        cmd += ["--device-map", args.device_map]
    for item in args.max_memory or []:
        cmd += ["--max-memory", item]
    if args.max_gated_modules is not None:
        cmd += ["--max-gated-modules", str(args.max_gated_modules)]
    if gate_checkpoint:
        cmd += ["--gate-checkpoint", gate_checkpoint]
    if args.policy_model:
        cmd += ["--policy-model", args.policy_model]
    if args.disable_gates:
        cmd.append("--disable-gates")
    if args.behavior_span_reward_weight is not None:
        cmd += ["--behavior-span-reward-weight", str(args.behavior_span_reward_weight)]
    if args.store_token_logprobs or args.loss_granularity == "token":
        cmd.append("--store-token-logprobs")
    return cmd


def _update_command(
    args: argparse.Namespace,
    *,
    rollouts: Path,
    updates: Path,
    gate_checkpoint: str | None,
    iteration: int,
) -> list[str]:
    cmd = [
        sys.executable,
        str(REPO_ROOT / "scripts/train/opvec_update_gates_from_rollouts.py"),
        "--config",
        args.config,
        "--mode-manifest",
        args.mode_manifest,
        "--rollouts",
        str(rollouts),
        "--output",
        str(updates),
        "--max-steps",
        str(args.update_epochs),
        "--max-logprob-tokens",
        str(args.max_logprob_tokens),
        "--lr",
        str(args.lr),
        "--prior-loss-weight",
        str(args.prior_loss_weight),
        "--ppo-loss-weight",
        str(args.ppo_loss_weight),
        "--best-response-loss-weight",
        str(args.best_response_loss_weight),
        "--pairwise-loss-weight",
        str(args.pairwise_loss_weight),
        "--pairwise-margin",
        str(args.pairwise_margin),
        "--max-pairwise-pairs-per-row",
        str(args.max_pairwise_pairs_per_row),
        "--min-grad-norm-for-step",
        str(args.min_grad_norm_for_step),
        "--device",
        args.device,
        "--torch-dtype",
        args.torch_dtype,
        "--gate-parameterization",
        args.gate_parameterization,
        "--update-batch-size",
        str(args.update_batch_size),
        "--batch-loss-reduction",
        args.batch_loss_reduction,
        "--loss-granularity",
        args.loss_granularity,
        "--frontier-order",
        args.frontier_order,
        "--frontier-shuffle-seed",
        str(args.frontier_shuffle_seed if args.frontier_shuffle_seed is not None else int(args.seed + iteration - 1)),
    ]
    if args.recompute_frontier:
        cmd.append("--recompute-frontier")
    if args.length_normalize_logprob:
        cmd.append("--length-normalize-logprob")
    if args.length_normalize_policy_logprob:
        cmd.append("--length-normalize-policy-logprob")
    if args.task_normalize_advantages:
        cmd.append("--task-normalize-advantages")
    if args.positive_reward_threshold is not None:
        cmd += ["--positive-reward-threshold", str(args.positive_reward_threshold)]
    if args.max_coefficient_delta_from_init is not None:
        cmd += ["--max-coefficient-delta-from-init", str(args.max_coefficient_delta_from_init)]
    if args.weight_decay is not None:
        cmd += ["--weight-decay", str(args.weight_decay)]
    if args.device_map:
        cmd += ["--device-map", args.device_map]
    for item in args.max_memory or []:
        cmd += ["--max-memory", item]
    if args.max_gated_modules is not None:
        cmd += ["--max-gated-modules", str(args.max_gated_modules)]
    if gate_checkpoint:
        cmd += ["--init-gate-checkpoint", gate_checkpoint]
    for item in args.task_weight or []:
        cmd += ["--task-weight", item]
    for item in args.category_weight or []:
        cmd += ["--category-weight", item]
    for item in args.source_weight or []:
        cmd += ["--source-weight", item]
    for item in args.frontier_task_quota or []:
        cmd += ["--frontier-task-quota", item]
    for item in args.train_coefficient or []:
        cmd += ["--train-coefficient", item]
    if args.use_retention:
        cmd.append("--use-retention")
    if args.max_retention_rows is not None:
        cmd += ["--max-retention-rows", str(args.max_retention_rows)]
    if args.retention_loss_weight is not None:
        cmd += ["--retention-loss-weight", str(args.retention_loss_weight)]
    return cmd


def _run(cmd: list[str]) -> None:
    print("[gated-grpo]", _fmt_cmd(cmd), flush=True)
    subprocess.run(cmd, cwd=str(REPO_ROOT), check=True)


def _fmt_cmd(cmd: list[str]) -> str:
    return " ".join(shlex.quote(str(item)) for item in cmd)


def _write_json(path: Path, payload: dict) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, ensure_ascii=False, indent=2, sort_keys=True) + "\n", encoding="utf-8")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--config", default="configs/gated_grpo.yaml")
    parser.add_argument("--seed-manifest", default=None)
    parser.add_argument("--mode-manifest", required=True)
    parser.add_argument("--run-dir", required=True)
    parser.add_argument("--run-id", default="gated-grpo")
    parser.add_argument("--num-iters", type=int, default=1)
    parser.add_argument("--num-prompts", type=int, default=150)
    parser.add_argument("--samples-per-prompt", type=int, default=8)
    parser.add_argument("--tasks", default=None, help="Optional comma-separated task filter, e.g. tool,code,memory")
    parser.add_argument("--memory-kind", default=None)
    parser.add_argument("--prompt-id", default=None)
    parser.add_argument("--use-manifest-order", action="store_true")
    parser.add_argument("--seed", type=int, default=20260510)
    parser.add_argument("--init-gate-checkpoint", default=None)
    parser.add_argument("--gate-parameterization", choices=["global", "layer-band", "parameter", "global-parameter"], default="global")
    parser.add_argument("--max-gated-modules", type=int, default=None, help="Default/all; use 1 for smoke test")
    parser.add_argument("--max-new-tokens", type=int, default=512)
    parser.add_argument("--max-prompt-tokens", type=int, default=2048)
    parser.add_argument("--max-logprob-tokens", type=int, default=3072)
    parser.add_argument("--temperature", type=float, default=0.7)
    parser.add_argument("--top-p", type=float, default=0.95)
    parser.add_argument("--greedy", action="store_true")
    parser.add_argument("--device", default="cuda")
    parser.add_argument("--device-map", default=None)
    parser.add_argument("--max-memory", action="append", default=[])
    parser.add_argument("--torch-dtype", default="bfloat16")
    parser.add_argument("--policy-model", default=None)
    parser.add_argument("--disable-gates", action="store_true")
    parser.add_argument("--behavior-span-reward-weight", type=float, default=None)
    parser.add_argument("--store-token-logprobs", action="store_true")
    parser.add_argument("--progress-every", type=int, default=10)

    parser.add_argument("--update-epochs", type=int, default=1, help="GRPO epochs over each collected on-policy rollout file")
    parser.add_argument("--update-batch-size", type=int, default=1)
    parser.add_argument("--batch-loss-reduction", choices=["mean", "sum"], default="mean")
    parser.add_argument("--loss-granularity", choices=["sequence", "token"], default="sequence")
    parser.add_argument("--frontier-order", choices=["as-is", "shuffle", "task-interleaved"], default="as-is")
    parser.add_argument("--frontier-shuffle-seed", type=int, default=None)
    parser.add_argument("--lr", type=float, default=0.01)
    parser.add_argument("--weight-decay", type=float, default=None)
    parser.add_argument("--prior-loss-weight", type=float, default=0.01)
    parser.add_argument("--ppo-loss-weight", type=float, default=1.0)
    parser.add_argument("--best-response-loss-weight", type=float, default=0.0)
    parser.add_argument("--pairwise-loss-weight", type=float, default=0.0)
    parser.add_argument("--pairwise-margin", type=float, default=0.0)
    parser.add_argument("--max-pairwise-pairs-per-row", type=int, default=0)
    parser.add_argument("--length-normalize-logprob", action="store_true")
    parser.add_argument("--length-normalize-policy-logprob", action="store_true")
    parser.add_argument("--task-normalize-advantages", action="store_true")
    parser.add_argument("--positive-reward-threshold", type=float, default=None)
    parser.add_argument("--min-grad-norm-for-step", type=float, default=0.0)
    parser.add_argument("--max-coefficient-delta-from-init", type=float, default=0.20)
    parser.add_argument("--recompute-frontier", action="store_true")
    parser.add_argument("--task-weight", action="append", default=[])
    parser.add_argument("--category-weight", action="append", default=[])
    parser.add_argument("--source-weight", action="append", default=[])
    parser.add_argument("--frontier-task-quota", action="append", default=[])
    parser.add_argument("--train-coefficient", action="append", default=[])
    parser.add_argument("--use-retention", action="store_true")
    parser.add_argument("--max-retention-rows", type=int, default=None)
    parser.add_argument("--retention-loss-weight", type=float, default=None)

    parser.add_argument("--bake-final", action="store_true")
    parser.add_argument("--bake-output", default=None)
    parser.add_argument("--plan-only-bake", action="store_true")
    parser.add_argument("--dry-run", action="store_true")
    return parser.parse_args()


if __name__ == "__main__":
    main()
