#!/usr/bin/env python3
"""Build the ICLR pairwise-zero diagnostic figure.

The figure is derived from the pairwise-zero diagnostics generated by
``build_rcrf_pairwise_zero_diagnostics.py``.  It is intended as a paper-facing
diagnostic figure: it summarizes which expert pairs conflict, what a zeroed
expert would remove, and why scalar zeroing is only a negative control.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd


ROOT = Path(__file__).resolve().parents[2]
DEFAULT_PAIRWISE_DIR = Path(
    "/tmp/shared-storage/ExpertGym/rcrf/code_hurt_subset_20260521/analysis/pairwise_zero_diagnostics_20260523"
)
DEFAULT_EVIDENCE = Path(
    "/tmp/shared-storage/ExpertGym/rcrf/code_hurt_subset_20260521/analysis/"
    "rcrf_paper_evidence_table_20260522/rcrf_paper_evidence_table.csv"
)
DEFAULT_FIGURE_DIR = ROOT / "docs/paper/ExpertGym_ICLR/figures"
DEFAULT_REPORT = ROOT / "docs/report/RCRF/20260523_iclr_pairwise_zero_figure.md"

PAIR_LABELS = {
    "tool_memory__code_zero": "Tool + Memory\n(Code = 0)",
    "tool_code__memory_zero": "Tool + Code\n(Memory = 0)",
    "memory_code__tool_zero": "Memory + Code\n(Tool = 0)",
}
TASKS = ["tool", "memory", "code"]
ROLE_COLUMNS = [
    ("role_code_repair_only", "Code repair"),
    ("role_shared_positive", "Shared +"),
    ("role_code_repair_vs_protected_harm", "Repair/harm"),
    ("role_code_negative_but_protected_support", "Behavior support"),
    ("role_code_source_conflict_with_behavior", "Source conflict"),
    ("role_uninformative", "Weak"),
]


def main() -> None:
    args = parse_args()
    pairwise_dir = Path(args.pairwise_dir).expanduser().resolve()
    figure_dir = Path(args.figure_dir).expanduser().resolve()
    figure_dir.mkdir(parents=True, exist_ok=True)

    conflict = pd.read_csv(pairwise_dir / "pairwise_conflict_summary.csv")
    zero = pd.read_csv(pairwise_dir / "zero_expert_summary.csv")
    evidence = pd.read_csv(Path(args.evidence).expanduser())

    output_pdf = figure_dir / "pairwise_zero_diagnostics.pdf"
    output_png = figure_dir / "pairwise_zero_diagnostics.png"
    build_figure(conflict, zero, evidence, output_pdf, output_png)
    summary = build_summary(conflict, zero, evidence, output_pdf, output_png)
    write_json(figure_dir / "pairwise_zero_diagnostics_summary.json", summary)
    write_report(Path(args.report).expanduser(), summary)
    print(json.dumps({"pdf": str(output_pdf), "png": str(output_png), "report": str(args.report)}, indent=2))


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--pairwise-dir", type=Path, default=DEFAULT_PAIRWISE_DIR)
    parser.add_argument("--evidence", type=Path, default=DEFAULT_EVIDENCE)
    parser.add_argument("--figure-dir", type=Path, default=DEFAULT_FIGURE_DIR)
    parser.add_argument("--report", type=Path, default=DEFAULT_REPORT)
    return parser.parse_args()


def build_figure(
    conflict: pd.DataFrame,
    zero: pd.DataFrame,
    evidence: pd.DataFrame,
    output_pdf: Path,
    output_png: Path,
) -> None:
    fig = plt.figure(figsize=(13.2, 4.5), constrained_layout=True)
    grid = fig.add_gridspec(1, 3, width_ratios=[1.0, 1.35, 1.0])
    ax0 = fig.add_subplot(grid[0, 0])
    ax1 = fig.add_subplot(grid[0, 1])
    ax2 = fig.add_subplot(grid[0, 2])

    draw_conflict_panel(ax0, conflict)
    draw_removed_role_panel(ax1, zero)
    draw_negative_control_panel(ax2, evidence)

    output_pdf.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(output_pdf, bbox_inches="tight")
    fig.savefig(output_png, dpi=240, bbox_inches="tight")
    plt.close(fig)


def draw_conflict_panel(ax: plt.Axes, conflict: pd.DataFrame) -> None:
    pair_names = list(PAIR_LABELS)
    matrix = np.full((len(pair_names), len(TASKS)), np.nan)
    for i, pair_name in enumerate(pair_names):
        for j, task in enumerate(TASKS):
            row = conflict[(conflict["pair_name"] == pair_name) & (conflict["task"] == task)]
            if row.empty or int(row["comparable_modules"].iloc[0]) <= 0:
                continue
            matrix[i, j] = float(row["opposite_sign_rate"].iloc[0])

    masked = np.ma.masked_invalid(matrix)
    cmap = plt.cm.Reds.copy()
    cmap.set_bad("#e8e8e8")
    im = ax.imshow(masked, cmap=cmap, vmin=0.0, vmax=0.75)
    ax.set_title("A. Pairwise conflict is task-span specific", fontsize=10, pad=8)
    ax.set_xticks(range(len(TASKS)), ["Tool", "Memory", "Code"], fontsize=8)
    ax.set_yticks(range(len(pair_names)), [PAIR_LABELS[name] for name in pair_names], fontsize=8)
    for i in range(matrix.shape[0]):
        for j in range(matrix.shape[1]):
            value = matrix[i, j]
            text = "N/A" if np.isnan(value) else f"{value:.2f}"
            ax.text(j, i, text, ha="center", va="center", fontsize=8)
    cbar = plt.colorbar(im, ax=ax, fraction=0.046, pad=0.04)
    cbar.set_label("opposite-sign rate", fontsize=8)
    cbar.ax.tick_params(labelsize=7)


def draw_removed_role_panel(ax: plt.Axes, zero: pd.DataFrame) -> None:
    zero = zero.set_index("pair_name").loc[list(PAIR_LABELS)].reset_index()
    bottoms = np.zeros(len(zero))
    colors = ["#4C78A8", "#72B7B2", "#F58518", "#54A24B", "#E45756", "#B279A2"]
    for (column, label), color in zip(ROLE_COLUMNS, colors):
        values = zero[column].astype(float).to_numpy()
        ax.bar(
            [PAIR_LABELS[name] for name in zero["pair_name"]],
            values,
            bottom=bottoms,
            label=label,
            color=color,
            alpha=0.9,
        )
        bottoms += values
    ax.set_title("B. Zeroing an expert removes mixed residual roles", fontsize=10, pad=8)
    ax.set_ylabel("removed residual rows", fontsize=8)
    ax.tick_params(axis="x", labelsize=8)
    ax.tick_params(axis="y", labelsize=8)
    ax.legend(loc="upper right", fontsize=7, frameon=False)
    ax.spines[["top", "right"]].set_visible(False)


def draw_negative_control_panel(ax: plt.Axes, evidence: pd.DataFrame) -> None:
    rows = {}
    for _, row in evidence.iterrows():
        short = str(row.get("short") or "")
        if short == "v9":
            rows["v9"] = row
        if short == "v15":
            rows["code=0"] = row
    labels = ["Memory F1", "Code hurt BoN", "Code hurt Acc"]
    values = {
        "v9": [
            float(rows["v9"]["memory_eval50_f1"]),
            float(rows["v9"]["code_hurt_bon_mean"]),
            float(rows["v9"]["code_hurt_acc_mean"]),
        ],
        "code=0": [
            float(rows["code=0"]["memory_eval50_f1"]),
            float(rows["code=0"]["code_hurt_bon_mean"]),
            float(rows["code=0"]["code_hurt_acc_mean"]),
        ],
    }
    x = np.arange(len(labels))
    width = 0.34
    ax.bar(x - width / 2, values["v9"], width, label="Reference", color="#4C78A8")
    ax.bar(x + width / 2, values["code=0"], width, label="Code = 0", color="#E45756")
    ax.set_xticks(x, labels, rotation=20, ha="right", fontsize=8)
    ax.set_ylim(0, max(max(v) for v in values.values()) * 1.25)
    ax.set_title("C. Scalar zeroing is a negative control", fontsize=10, pad=8)
    ax.tick_params(axis="y", labelsize=8)
    ax.legend(loc="upper right", fontsize=8, frameon=False)
    ax.grid(axis="y", linewidth=0.4, alpha=0.3)
    ax.spines[["top", "right"]].set_visible(False)


def build_summary(
    conflict: pd.DataFrame,
    zero: pd.DataFrame,
    evidence: pd.DataFrame,
    output_pdf: Path,
    output_png: Path,
) -> dict[str, Any]:
    conflict_rows = []
    for _, row in conflict.iterrows():
        conflict_rows.append(
            {
                "pair_name": str(row["pair_name"]),
                "task": str(row["task"]),
                "comparable_modules": int(row["comparable_modules"]),
                "opposite_sign_rate": None
                if int(row["comparable_modules"]) <= 0
                else float(row["opposite_sign_rate"]),
                "both_positive_rate": None
                if int(row["comparable_modules"]) <= 0
                else float(row["both_positive_rate"]),
            }
        )
    zero_rows = [
        {
            "pair_name": str(row["pair_name"]),
            "zero_expert": str(row["zero_expert"]),
            "removed_rows": int(row["removed_rows"]),
            "code_repair_only": int(row["role_code_repair_only"]),
            "shared_positive": int(row["role_shared_positive"]),
            "memory_support_rows": int(row["memory_support_rows"]),
            "tool_support_rows": int(row["tool_support_rows"]),
        }
        for _, row in zero.iterrows()
    ]
    return {
        "figure_pdf": str(output_pdf),
        "figure_png": str(output_png),
        "conflict_rows": conflict_rows,
        "zero_rows": zero_rows,
        "claim": (
            "Pairwise-zero diagnostics show that each expert removal deletes a mixture of capability, "
            "behavior-support, and conflict residuals; scalar zeroing is therefore useful as a negative "
            "control but not as a composition method."
        ),
    }


def write_json(path: Path, payload: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8") as handle:
        json.dump(payload, handle, ensure_ascii=False, indent=2, sort_keys=True)
        handle.write("\n")


def write_report(path: Path, summary: dict[str, Any]) -> None:
    lines = [
        "# ICLR Pairwise-Zero Diagnostic Figure",
        "",
        f"PDF: `{summary['figure_pdf']}`",
        f"PNG: `{summary['figure_png']}`",
        "",
        "## What The Figure Shows",
        "",
        "1. Pairwise conflict is task-span specific; missing behavior probes are explicitly shown as `N/A`, not as zero conflict.",
        "2. Zeroing one expert removes mixed residual roles, so an expert cannot be interpreted as pure ability or pure noise.",
        "3. The existing `code=0` ablation increases Memory but damages Code, making scalar zeroing a negative control rather than a method.",
        "",
        "## Paper-Safe Claim",
        "",
        summary["claim"],
        "",
        "## Pairwise Conflict Rows",
        "",
        "| pair | task | comparable modules | opposite-sign rate | both-positive rate |",
        "| --- | --- | ---: | ---: | ---: |",
    ]
    for row in summary["conflict_rows"]:
        opp = "N/A" if row["opposite_sign_rate"] is None else f"{row['opposite_sign_rate']:.4f}"
        both = "N/A" if row["both_positive_rate"] is None else f"{row['both_positive_rate']:.4f}"
        lines.append(f"| {row['pair_name']} | {row['task']} | {row['comparable_modules']} | {opp} | {both} |")
    lines.extend(["", "## Zeroed Expert Role Rows", "", "| pair | zero expert | code repair | shared positive | memory support | tool support |", "| --- | --- | ---: | ---: | ---: | ---: |"])
    for row in summary["zero_rows"]:
        lines.append(
            f"| {row['pair_name']} | {row['zero_expert']} | {row['code_repair_only']} | "
            f"{row['shared_positive']} | {row['memory_support_rows']} | {row['tool_support_rows']} |"
        )
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


if __name__ == "__main__":
    main()
