#!/usr/bin/env bash
set -euo pipefail

# Exp F, 2026-05-16: init task-vector coefficients at 1.0, train with
# GRPO + retention only. OPD is intentionally disabled.

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
cd "$REPO_ROOT"

export PY="${PY:-/mnt/cache/wuruixiao/miniconda3/envs/BFCL/bin/python}"
export ROOT="${ROOT:-/tmp/shared-storage/OnPolicy}"
export ONPOLICY_STORAGE_ROOT="${ONPOLICY_STORAGE_ROOT:-$ROOT}"
export PYTHONUNBUFFERED="${PYTHONUNBUFFERED:-1}"
export PYTHONDONTWRITEBYTECODE="${PYTHONDONTWRITEBYTECODE:-1}"

CALIBRATION="${CALIBRATION:-$ROOT/data/calibration/qbank_c033333_paper96_balanced32_seed20260514.prompts.jsonl}"
MODE="${MODE:-$ROOT/modes/opvec4/mode_manifest.json}"
INIT_GATE_CHECKPOINT="${INIT_GATE_CHECKPOINT:-$ROOT/data/question_bank/ta_avgvec_c033333_hotpotqa_v1/init_gates/init_global_parameter_c1.json}"
RUN_NAME="${RUN_NAME:-expF_init1_grpo_ret_20260516}"
RUN_DIR="${RUN_DIR:-$ROOT/runs/gated_grpo/$RUN_NAME}"

require_file() {
  if [[ ! -f "$1" ]]; then
    echo "[error] missing required file: $1" >&2
    exit 2
  fi
}

require_file "$CALIBRATION"
require_file "$MODE"
require_file "$INIT_GATE_CHECKPOINT"

STRATEGY=global-parameter \
INIT_VALUE=1.0 \
INIT_GATE_CHECKPOINT="$INIT_GATE_CHECKPOINT" \
CONFIG=configs/gated_grpo.yaml \
MODE="$MODE" \
CALIBRATION="$CALIBRATION" \
RUN_NAME="$RUN_NAME" \
RUN_DIR="$RUN_DIR" \
GPU_LIST="${GPU_LIST:-2,3}" \
ROLLOUT_GPUS="${ROLLOUT_GPUS:-${GPU_LIST:-2,3}}" \
NUM_ITERS="${NUM_ITERS:-20}" \
NUM_PROMPTS="${NUM_PROMPTS:-96}" \
SAMPLES_PER_PROMPT="${SAMPLES_PER_PROMPT:-4}" \
STORE_TOKEN_LOGPROBS=0 \
OPTIMIZER=sgd \
SGD_MOMENTUM=0.2 \
PERSIST_OPTIMIZER_STATE=1 \
LR="${LR:-0.1876}" \
PRIOR_LOSS_WEIGHT=0.0 \
MAX_COEFF_DELTA=1.0 \
UPDATE_EPOCHS=1 \
UPDATE_BATCH_SIZE=4 \
BATCH_LOSS_REDUCTION=mean \
OPTIMIZER_STEP_SCOPE=epoch \
LOSS_GRANULARITY=sequence \
FRONTIER_ORDER=task-interleaved \
FRONTIER_TOOL_QUOTA=32 \
FRONTIER_MEMORY_QUOTA=32 \
FRONTIER_CODE_QUOTA=32 \
PPO_LOSS_WEIGHT=1.0 \
BEST_RESPONSE_LOSS_WEIGHT=0.0 \
PAIRWISE_LOSS_WEIGHT=0.0 \
USE_RETENTION=1 \
RETENTION_OBJECTIVE=nll \
RETENTION_POSITIVE_REWARD_THRESHOLD=1.0 \
RETENTION_TASK_BALANCED_LOSS_SCALE=1 \
RETENTION_SCALE_TARGET=0.5 \
OPD_LOSS_WEIGHT=0.0 \
OPD_PAIRWISE_LOSS_WEIGHT=0.0 \
OPD_DISTILL_ROLLOUT= \
DYNAMIC_OPD_EXPERT_ROLLOUT= \
DYNAMIC_OPD_TASKS=tool,memory,code \
OPD_POSITIVE_REWARD_THRESHOLD=1.0 \
OPD_LENGTH_NORMALIZE_LOGPROB=1 \
RETENTION_LENGTH_NORMALIZE_LOGPROB=1 \
OPD_TASK_BALANCED_LOSS_SCALE=1 \
LENGTH_NORMALIZE_POLICY_LOGPROB=1 \
LENGTH_NORMALIZE_LOGPROB=0 \
TASK_NORMALIZE_ADVANTAGES=0 \
ADVANTAGE_NORMALIZATION=centered \
USE_FRONTIER_WEIGHT=0 \
MAX_NEW_TOKENS=1024 \
TOOL_MAX_NEW_TOKENS=512 \
CODE_MAX_NEW_TOKENS=4096 \
MEMORY_UPDATE_MAX_NEW_TOKENS=2048 \
MEMORY_FINAL_MAX_NEW_TOKENS=2048 \
MAX_PROMPT_TOKENS=8192 \
MAX_MODEL_LEN=12288 \
MAX_LOGPROB_TOKENS=12288 \
ROLLOUT_BATCH_SIZE=32 \
ROLLOUT_SHARDS=auto \
TENSOR_PARALLEL_SIZE=1 \
GPU_MEMORY_UTILIZATION=0.82 \
TEMPERATURE=0.7 \
TOP_P=0.95 \
SEED_VALUE=20260516 \
PROGRESS_EVERY=10 \
DRY_RUN="${DRY_RUN:-0}" \
bash skill/command/run_qbank_c033333_gate_strategy.sh
