#!/usr/bin/env bash
set -euo pipefail

# Exp H, 2026-05-17: B-style paper96 calibration with direct global
# coefficients. Train the three expert scalars with GRPO + dynamic OPD +
# retention from the 1/3 task-vector initialization.

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
cd "$REPO_ROOT"

export PY="${PY:-/mnt/cache/wuruixiao/miniconda3/envs/BFCL/bin/python}"
export ROOT="${ROOT:-/tmp/shared-storage/OnPolicy}"
export ONPOLICY_STORAGE_ROOT="${ONPOLICY_STORAGE_ROOT:-$ROOT}"
export PYTHONUNBUFFERED="${PYTHONUNBUFFERED:-1}"
export PYTHONDONTWRITEBYTECODE="${PYTHONDONTWRITEBYTECODE:-1}"

CALIBRATION="${CALIBRATION:-$ROOT/data/calibration/qbank_c033333_paper96_balanced32_seed20260514.prompts.jsonl}"
MODE="${MODE:-$ROOT/modes/opvec4/mode_manifest.json}"
INIT_GATE_CHECKPOINT="${INIT_GATE_CHECKPOINT:-$ROOT/data/question_bank/ta_avgvec_c033333_hotpotqa_v1/init_gates/init_global_coefficient_c033333.json}"
RUN_NAME="${RUN_NAME:-expH_gc_c033333_grpo_opd_ret_20260517}"
RUN_DIR="${RUN_DIR:-$ROOT/runs/gated_grpo/$RUN_NAME}"
EXPERT_DIR="${EXPERT_DIR:-$ROOT/data/calibration/paper96_expert_rollouts_seed20260514}"
CODE_AUG_DIR="${CODE_AUG_DIR:-$ROOT/data/calibration/20260516_code_opd_aug}"

TOOL_EXPERT="$EXPERT_DIR/tool_expert_paper96_s2_seed20260514.jsonl"
MEMORY_EXPERT="$EXPERT_DIR/memory_expert_paper96_s2_seed20260514.jsonl"
CODE_EXPERT_OLD="$EXPERT_DIR/code_expert_paper96_s2_seed20260514.jsonl"
CODE_EXPERT_REASONFLUX="$CODE_AUG_DIR/code_expert_reasonflux_coder7b_s8_seed20260516.jsonl"
CODE_EXPERT_REASONFLUX2="$CODE_AUG_DIR/code_expert_reasonflux_coder7b_s8_seed20260517.jsonl"
CODE_EXPERT_DEEPSEEK="$CODE_AUG_DIR/code_expert_deepseek_r1_distill_qwen7b_s8_seed20260516.jsonl"
CODE_EXPERT_MEMORY="$CODE_AUG_DIR/code_expert_rl_memoryagent7b_s8_seed20260516.jsonl"

require_file() {
  if [[ ! -f "$1" ]]; then
    echo "[error] missing required file: $1" >&2
    exit 2
  fi
}

for path in \
  "$CALIBRATION" \
  "$MODE" \
  "$INIT_GATE_CHECKPOINT" \
  "$TOOL_EXPERT" \
  "$MEMORY_EXPERT" \
  "$CODE_EXPERT_OLD" \
  "$CODE_EXPERT_REASONFLUX" \
  "$CODE_EXPERT_REASONFLUX2" \
  "$CODE_EXPERT_DEEPSEEK" \
  "$CODE_EXPERT_MEMORY"; do
  require_file "$path"
done

DYNAMIC_OPD_EXPERT_ROLLOUT="$TOOL_EXPERT,$MEMORY_EXPERT,$CODE_EXPERT_OLD,$CODE_EXPERT_REASONFLUX,$CODE_EXPERT_DEEPSEEK,$CODE_EXPERT_MEMORY,$CODE_EXPERT_REASONFLUX2"

STRATEGY=global-coefficient \
INIT_VALUE=0.3333333333333333 \
INIT_GATE_CHECKPOINT="$INIT_GATE_CHECKPOINT" \
CONFIG=configs/gated_grpo.yaml \
MODE="$MODE" \
CALIBRATION="$CALIBRATION" \
RUN_NAME="$RUN_NAME" \
RUN_DIR="$RUN_DIR" \
GPU_LIST="${GPU_LIST:-2,3}" \
ROLLOUT_GPUS="${ROLLOUT_GPUS:-${GPU_LIST:-2,3}}" \
NUM_ITERS="${NUM_ITERS:-20}" \
NUM_PROMPTS="${NUM_PROMPTS:-96}" \
SAMPLES_PER_PROMPT="${SAMPLES_PER_PROMPT:-4}" \
STORE_TOKEN_LOGPROBS=0 \
OPTIMIZER=sgd \
SGD_MOMENTUM=0.2 \
PERSIST_OPTIMIZER_STATE=1 \
LR="${LR:-0.1876}" \
PRIOR_LOSS_WEIGHT=0.0 \
MAX_COEFF_DELTA=1.0 \
UPDATE_EPOCHS=1 \
UPDATE_BATCH_SIZE=4 \
BATCH_LOSS_REDUCTION=mean \
OPTIMIZER_STEP_SCOPE=epoch \
LOSS_GRANULARITY=sequence \
FRONTIER_ORDER=task-interleaved \
FRONTIER_TOOL_QUOTA=32 \
FRONTIER_MEMORY_QUOTA=32 \
FRONTIER_CODE_QUOTA=32 \
PPO_LOSS_WEIGHT=1.0 \
BEST_RESPONSE_LOSS_WEIGHT=0.0 \
PAIRWISE_LOSS_WEIGHT=0.0 \
USE_RETENTION=1 \
RETENTION_OBJECTIVE=nll \
RETENTION_POSITIVE_REWARD_THRESHOLD=1.0 \
RETENTION_TASK_BALANCED_LOSS_SCALE=1 \
RETENTION_SCALE_TARGET=0.5 \
OPD_LOSS_WEIGHT=1.0 \
OPD_PAIRWISE_LOSS_WEIGHT=0.0 \
DYNAMIC_OPD_EXPERT_ROLLOUT="$DYNAMIC_OPD_EXPERT_ROLLOUT" \
DYNAMIC_OPD_TASKS=tool,memory,code \
DYNAMIC_OPD_KEY=prompt_id \
DYNAMIC_OPD_CURRENT_MAX_SUCCESS=0 \
DYNAMIC_OPD_POSITIVE_THRESHOLD=1.0 \
DYNAMIC_OPD_MAX_POSITIVES_PER_ROW=1 \
DYNAMIC_OPD_MAX_NEGATIVES_PER_ROW=2 \
DYNAMIC_OPD_PER_TASK=32 \
OPD_POSITIVE_REWARD_THRESHOLD=1.0 \
OPD_LENGTH_NORMALIZE_LOGPROB=1 \
RETENTION_LENGTH_NORMALIZE_LOGPROB=1 \
OPD_TASK_BALANCED_LOSS_SCALE=1 \
LENGTH_NORMALIZE_POLICY_LOGPROB=1 \
LENGTH_NORMALIZE_LOGPROB=0 \
TASK_NORMALIZE_ADVANTAGES=0 \
ADVANTAGE_NORMALIZATION=centered \
USE_FRONTIER_WEIGHT=0 \
MAX_NEW_TOKENS=1024 \
TOOL_MAX_NEW_TOKENS=512 \
CODE_MAX_NEW_TOKENS=4096 \
MEMORY_UPDATE_MAX_NEW_TOKENS=2048 \
MEMORY_FINAL_MAX_NEW_TOKENS=2048 \
MAX_PROMPT_TOKENS=8192 \
MAX_MODEL_LEN=12288 \
MAX_LOGPROB_TOKENS=12288 \
ROLLOUT_BATCH_SIZE=32 \
ROLLOUT_SHARDS=auto \
TENSOR_PARALLEL_SIZE=1 \
GPU_MEMORY_UTILIZATION=0.82 \
TEMPERATURE=0.7 \
TOP_P=0.95 \
SEED_VALUE=20260517 \
PROGRESS_EVERY=10 \
DRY_RUN="${DRY_RUN:-0}" \
bash skill/command/run_qbank_c033333_gate_strategy.sh
